# -*- coding: utf-8 -*-
"""scraping trabajo integrador.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rgIWoZNDFUWGcD23E5LQg9jl9KZnlh-X
"""

## https://www.youtube.com/watch?v=kPNHKrOqedI
## https://www.youtube.com/watch?v=XaHC6axF5kc
##ORDEN DE PRIORIDADES PARA BUSCAR ELEMENTOS 
##1 ID,   2 Class Name   3.Tag name, CSS Selector    4. Xpath
import requests
from bs4 import BeautifulSoup
import pandas as pd
pais = input("Ingrese 'argentina' o 'espana' : ")


website = 'https://datosmacro.expansion.com/otros/coronavirus/'+pais
print (website)


result = requests.get(website)
content = result.text
soup = BeautifulSoup(content, 'lxml')

box = soup.find('section', class_='col-sm-8 col-sm-8-asd')#este es el elemento raiz que contiene el elemento que nos interesa.
#cuando usamos .find(tag, clase) se pone primero el tag luego la clase que copiamos.-

titulo = box.find('div', class_='tabletit').get_text()
#aca utilizamos .get_text() para traer el texto del titulo seleccionado. en caso de no poseer clase solo se pone el TAG.
#tener en cuenta que el find se hizo dentro de box y no en soup.
# probar ---> print (titulo)

filas= box.find('div', class_ = 'table-responsive').find('tbody').find_all('tr')
##BUSCA DENTRO DE div la clase table responsive, dentro de ese div busca todo los elementos de tbody, y dentro de tbody busca todos los tr.

print (len(filas)) #aca imprimo la cantidad de filas que hay en la tabla
#---> filas[0].find_all('td')[1].get_text()      #aca traigo de todas las filas la fila '0' y de la fila cero la columna '1', luego convierto el html a texto.


dias = []
incre_muertos = []
muertos = []
muertosxmill = []
incremenConfir= []
confir = []
confircm14dias = []
for fila in filas:
    dias.append(fila.find_all('td')[0].get_text()) 
    incre_muertos.append(fila.find_all('td')[1].get_text()) 
    muertos.append(fila.find_all('td')[2].get_text()) 
    muertosxmill.append(fila.find_all('td')[3].get_text()) 
    incremenConfir.append(fila.find_all('td')[4].get_text()) 
    confir.append(fila.find_all('td')[5].get_text()) 
    confircm14dias.append(fila.find_all('td')[6].get_text()) 

    

df = pd.DataFrame({
    "Fecha":dias,
    "Incremento Muertos":incre_muertos,
    "Muertos":muertos,
    "Muertos/Millon":muertosxmill,
    "Incremento Confirmados":incremenConfir,
    "Confirmados":confir,
    "Confirmados/100.000-14 Dias":confircm14dias
})

#exportamos el dataframe a csv abajo

df.to_csv('COVID '+pais+'.csv')